### ISSUE TITLE
`this.props.children` is always empty within component

### ISSUE THREAD

**Issue by corstian** [bryanrsmith/aurelia-react-loader#2]
Having the following component:

```
import React from 'react';

export class MyReactComponent extends React.Component {
  render() {
    console.log(this);
    let { name, onClick } = this.props;
    return (<button onClick={onClick}>Hello, {name}</button>);
  }
}
```

and using it in html like this:

```
<require from="components/my-react-component!react-component"></require>
<my-react-component><h2>lol</h2><h2>lol</h2></my-react-component>
```

I'd expect `this.props.children` to be an array with 2 children. Therefore even `this.props` is empty.

Is this my fault or isn't it supported by the loader?

**Comment by bryanrsmith** [comment]
Top-level children are currently not supported. _Maybe_ I could add support for static child elements, but because of the interop layer required between the two frameworks I don't think it will be possible to add full correct support for children. Your best bet will be to pass the data from aurelia to React via the props binding to a new React element that passes children down as needed.
